import { base_url } from '@/base_url';
import RootLayout from '@/layout/RootLayout';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';

const CategoryWiseProduct = () => {
    const router = useRouter();
  
    return (
        <div>
            <Head>
                <title>Product Category</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                product category {router.query.category}
            </div>
        </div>
    );
};

export default CategoryWiseProduct;
CategoryWiseProduct.getLayout = function getLayout(page) {
    return (
      <RootLayout>
        {page}
      </RootLayout>
    )
  }
// export const getServerSideProps = async (context) => {
//     const { params } = context
//     const res = await fetch(`${base_url}/${params.category}`)
//     const data = await res.json()
//     return {
//         props: {
//             news: data
//         }
//     }
// }