import { base_url } from '@/base_url';
import RootLayout from '@/layout/RootLayout';
import { useGetProductsByCategoryQuery } from '@/redux/api/api';
import { Card, Col, Row } from 'antd';

import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';

const CategoryWiseProduct = () => {
  const router = useRouter();
  let query = null
  if (router.query?.category?.includes('motherboard')) {
    query = "Motherboard"
  } else if (router.query?.category?.includes('processor')) {
    query = "Processor"
  }
  else if (router.query?.category?.includes('ram')) {
    query = "RAM"
  }
  else if (router.query?.category?.includes('power-supply')) {
    query = "Power Supply Unit"
  }
  else if (router.query?.category?.includes('storage')) {
    query = "Storage Device"
  }
  else if (router.query?.category?.includes('monitor')) {
    query = "Monitor"
  }
  else if (router.query?.category?.includes('others')) {
    query = "Others"
  }
  const { data } = useGetProductsByCategoryQuery(query)

  return (
    <div>
      <Head>
        <title>Product Category</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>
          <p style={{
            fontSize: '2rem',
            marginTop: "40px",
            marginBottom: "20px"
          }} >{query}</p>
          <Row gutter={[16, 16]}>
            {data?.data?.map((product) => (
              <Col key={product._id} className="gutter-row"
                xs={{
                  span: 24,
                }}
                sm={{
                  span: 12,
                }}
                md={{
                  span: 8,
                }}
                lg={{
                  span: 6,

                }}>
                <Card
                  onClick={() => {
                    router.push(`/product-details/${product._id}`)
                  }}
                  hoverable
                  style={{
                    width: 240,
                    height: 400
                  }}
                  cover={<img alt="example" src={product.image} style={{ padding: "5px", height: "200px", width: "100%" }} />}
                >
                  {/* <Meta title="Europe Street beat" description="www.instagram.com" /> */}
                  <span>{product.productName}</span>
                  <p>{product.category}</p>
                  <p>{product.price}</p>
                  <p>{product.status}</p>
                </Card>
              </Col>
            ))}
          </Row>
        </div>
      </div>
    </div>
  );
};

export default CategoryWiseProduct;
CategoryWiseProduct.getLayout = function getLayout(page) {
  return (
    <RootLayout>
      {page}
    </RootLayout>
  )
}
// export const getServerSideProps = async (context) => {
//     const { params } = context
//     const res = await fetch(`${base_url}/${params.category}`)
//     const data = await res.json()
//     return {
//         props: {
//             news: data
//         }
//     }
// }