import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import RootLayout from '@/layout/RootLayout'
import { Card, Col, Row } from 'antd'
import { base_url } from '@/base_url'
import { loadProduct } from '@/apicall/products'
import { useSession } from "next-auth/react";
import { useGetCategoriesQuery, useGetProductsQuery } from '@/redux/api/api'
import { useRouter } from 'next/router'
const { Meta } = Card;
const inter = Inter({ subsets: ['latin'] })

export default function Homepage() {
  const { data, isLoading } = useGetProductsQuery(undefined)
  // const { data: categories } = useGetCategoriesQuery(undefined)
  // console.log("🚀 ~ file: index.js:18 ~ Homepage ~ categories:", categories)
  const categories = [
    {
      category: "Monitor",
      link: "monitor",
      image: "https://www.cnet.com/a/img/resize/8d47065f9ecb62603a14d9b33f02e3e5c91a512e/hub/2021/05/12/0ad36336-efa0-4310-aff2-c268fec45350/samsung-lf27t350fhnxza-monitor.png?auto=webp&fit=crop&height=900&precrop=885,498,x0,y0&width=1200"
    },
    {
      category: "Processor",
      link: "processor",
      image: "https://insider-gaming.com/wp-content/uploads/2022/12/amd-ryzen-cpu.png"
    },
    {
      category: "Motherboard",
      link: "motherboard",
      image: "https://greentech.com.bd/image/cache/catalog/b550m-ds3h-ac-ud-550x550.jpg"
    },
    {
      category: "RAM",
      link: "ram",
      image:'https://assets-prd.ignimgs.com/2022/06/24/corsair-dominator-platinum-rgb-1656107201735.jpg'
  },
  {
    category:"Storage Devices",
    link:"storage",
    image:"https://i.pcmag.com/imagery/articles/07hyeZ8Gp093k9bdVYUCX8p-20.fit_lim.size_1200x630.v1599074618.jpg"
  },
  {
    category:"Power Supply",
    link:"power-supply",
    image:'https://www.ultratech.com.bd/image/cache/catalog/power-supply/antec/meta-v450/antec-meta-v450-power-supply.jpg-500x500.jpg.webp'
  },
  {
    category:"Others",
    link:"others",
    image:'https://www.startech.com.bd/image/cache/catalog/keyboard/havit/kb380l/kb380l-01-500x500.webp'
  }
  ]
  const router = useRouter()

  return (
    <>
      <Head>
        <title>Pc Builder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <p style={{
          fontSize: '2rem',
          marginTop: "40px",
          marginBottom: "40px",
          textAlign:"center"
        }} >Featured Products</p>
        <Row gutter={[16, 16]}>
          {data?.data?.map((product) => (
            <Col key={product._id} className="gutter-row"
              xs={{
                span: 24,
              }}
              sm={{
                span: 12,
              }}
              md={{
                span: 8,
              }}
              lg={{
                span: 6,

              }}>
              <Card
                onClick={() => {
                  router.push(`/product-details/${product._id}`)
                }}
                hoverable
                style={{
                  width: 240,
                  height: 400
                }}
                cover={<img alt="example" src={product.image} style={{ padding: "5px", height: "200px", width: "100%" }} />}
              >
                {/* <Meta title="Europe Street beat" description="www.instagram.com" /> */}
                <span>{product.productName}</span>
                <p>{product.category}</p>
                <p>{product.price}</p>
                <p>{product.status}</p>
              </Card>
            </Col>
          ))}
        </Row>
        <p style={{
          fontSize: '2rem',
          marginTop: "40px",
          marginBottom: "40px",
          textAlign:"center"
        }} >Featured Categories</p>
        <Row gutter={[16, 16]} className="gutter-row">
          {
            categories.map((category, i) => (
              <Col key={i} xs={{
                span: 24,
              }}
                sm={{
                  span: 12,
                }}
                md={{
                  span: 8,
                }}
                lg={{
                  span: 6,

                }}>
                <Card
                  onClick={() => {
                    router.push(`/category/${category.link}`)
                  }}
                  hoverable

                  cover={<img alt="example" src={category?.image} style={{ padding: "5px", height: "200px", width: "100%" }} />}
                >
                  <p style={{ textAlign: "center", fontSize: "20px" }}>{category.category}</p>
                </Card>
              </Col>
            ))
          }

        </Row>
      </div>
    </>
  )
}
Homepage.getLayout = function getLayout(page) {
  return (
    <RootLayout>
      {page}
    </RootLayout>
  )
}
// export const getStaticProps = async () => {
//   const data = await loadProduct()
//   return {
//     props: {
//       allProducts: data.data
//     },
//     revalidate: 30
//   }
// }
