import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import RootLayout from '@/layout/RootLayout'
import { Card, Col, Row } from 'antd'
import { base_url } from '@/base_url'
// import { useSession } from "next-auth/react";
const { Meta } = Card;
const inter = Inter({ subsets: ['latin'] })

export default function Homepage({ allProducts }) {
  // const { data: session } = useSession()
  console.log("🚀 ~ file: index.js:10 ~ Homepage ~ allProducts:", allProducts)
  return (
    <>
      <Head>
        <title>Pc Builder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <p style={{
          fontSize: '2rem',
          marginTop: "40px",
          marginBottom:"20px"
        }} className={styles.texcenter}>Featured Products</p>
        <Row gutter={[16, 16]}>
          {allProducts?.map((product) => (
            <Col key={product._id} className="gutter-row"
              xs={{
                span: 24,
              }}
              sm={{
                span: 12,
              }}
              md={{
                span: 8,
              }}
              lg={{
                span: 6,

              }}>
              <Card
                hoverable
                style={{
                  width: 240,
                  height:400
                }}
                // cover={<Image alt="example" src={product.image} style={{padding:"5px",height:"200px",width:"100%"}} />}
              >
                {/* <Meta title="Europe Street beat" description="www.instagram.com" /> */}
                <span>{product.productName}</span>
                <p>{product.category}</p>
                <p>{product.price}</p>
                <p>{product.status}</p>
              </Card>
            </Col>
          ))}
        </Row>
      </div>
    </>
  )
}
Homepage.getLayout = function getLayout(page) {
  return (
    <RootLayout>
      {page}
    </RootLayout>
  )
}
export const getStaticProps = async () => {
  const res = await fetch(`${base_url}/api/products`)
  const data = await res.json()
  return {
    props: {
      allProducts: data.data
    },
    revalidate: 30
  }
}
