import RootLayout from '@/layout/RootLayout';
import { useGetProductsByIdQuery } from '@/redux/api/api';
import { Avatar, Col, Row } from 'antd';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import { UserOutlined } from '@ant-design/icons';
const ProductDetails = () => {
    const router = useRouter();
    const { data } = useGetProductsByIdQuery(router.query.productId?.toString())
    return (
        <div>
            <Head>
                <title>Product Details</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <h1 style={{
                    fontSize: '2rem',
                    marginTop: "40px",
                    marginBottom: "20px"
                }}>Product Details</h1>
                <Row gutter={[40, 16]}>

                    <Col
                        xs={{
                            span: 24,
                        }}
                        sm={{
                            span: 24,
                        }}
                        md={{
                            span: 12,
                        }}
                        lg={{
                            span: 12,

                        }}>
                        <img style={{ width: "100%", height: '400px', objectFit: "contain" }} src={data?.data.image} />

                    </Col >
                    <Col
                        xs={{
                            span: 24,
                        }}
                        sm={{
                            span: 24,
                        }}
                        md={{
                            span: 12,
                        }}
                        lg={{
                            span: 12,

                        }}
                        style={{ lineHeight: "1.8", fontWeight: 500 }}
                    >
                        <p>Product Name: {data?.data?.productName}</p>
                        <p>Category: {data?.data?.category}</p>
                        <p>Status: {data?.data?.status}</p>
                        <p>Price: ${data?.data?.price}</p>
                        <p>{data?.data?.description}</p>

                        <p style={{ fontWeight: "700" }}>Key Features</p>
                        {
                            data?.data?.keyFeatures.specification &&
                            <p>Specification: {data?.data?.keyFeatures.specification}</p>
                        }
                        {
                            data?.data?.keyFeatures.brand &&
                            <p>Brand: {data?.data?.keyFeatures.brand}</p>
                        }
                        {
                            data?.data?.keyFeatures.maxBoostClock &&
                            <p>Max Boost Clock: {data?.data?.keyFeatures.maxBoostClock}</p>
                        }
                        {
                            data?.data?.keyFeatures.Ethernet
                            &&
                            <p>Ethernet: {data?.data?.keyFeatures.Ethernet
                            }</p>
                        }
                        {
                            data?.data?.keyFeatures.memorySupport
                            &&
                            <p>Memory Support: {data?.data?.keyFeatures.memorySupport
                            }</p>
                        }
                        {
                            data?.data?.keyFeatures.USBPorts
                            &&
                            <p>USB Ports: {data?.data?.keyFeatures.USBPorts
                            }</p>
                        }
                        {
                            data?.data?.keyFeatures.capacity
                            &&
                            <p>Capacity: {data?.data?.keyFeatures.capacity
                            }</p>
                        }
                        {
                            data?.data?.keyFeatures.speed
                            &&
                            <p>Speed: {data?.data?.keyFeatures.speed
                            }</p>
                        }
                        {
                            data?.data?.keyFeatures.wattage
                            &&
                            <p>Wattage: {data?.data?.keyFeatures.wattage
                            }</p>
                        }
                        {
                            data?.data?.keyFeatures.efficiency
                            &&
                            <p>Efficiency: {data?.data?.keyFeatures.efficiency
                            }</p>
                        }
                        {
                            data?.data?.keyFeatures.resolution
                            &&
                            <p>Resolution: {data?.data?.keyFeatures.resolution
                            }</p>
                        }
                        {
                            data?.data?.keyFeatures.refreshRate
                            &&
                            <p>Refresh Rate: {data?.data?.keyFeatures.refreshRate
                            }</p>
                        }
                        {
                            data?.data?.keyFeatures.panelType
                            &&
                            <p>Panel Type: {data?.data?.keyFeatures.panelType
                            }</p>
                        }

                        <p >Individual Rating: {data?.data?.individualRating}</p>
                        <p>Average Rating: {data?.data?.averageRating}</p>

                    </Col>

                </Row>
                <div style={{ marginTop: "15px", marginBottom: "20px", display: "flex", justifyContent: 'center' }}>
                    <div>
                        {
                            data?.data?.reviews?.map((review, i) => (
                                <div style={{ marginTop: "10px" }} key={i}>
                                    <div style={{ display: "flex", gap: "10px", alignItems: "center" }}>
                                        <Avatar icon={<UserOutlined />} />
                                        <p style={{ fontSize: "16px", fontWeight: 600 }}>{review?.reviewer}</p>
                                    </div>
                                    <p style={{}}>{review?.comment}</p>
                                </div>
                            ))}
                    </div>
                </div>
            </div>
        </div>
    );
};

export default ProductDetails;

ProductDetails.getLayout = function getLayout(page) {
    return (
        <RootLayout>
            {page}
        </RootLayout>
    )
}
// export const getServerSideProps = async (context) => {
//     const { params } = context
//     const res = await fetch(`${base_url}/${params.category}`)
//     const data = await res.json()
//     return {
//         props: {
//             news: data
//         }
//     }
// }